Add comment to avoid bump of PMD Maven plugin 3.26.0 for now
- java.lang.NoSuchMethodError:
org.apache.maven.doxia.sink.Sink.verbatim()V
- Needs a new site plugin which does not work with our currents setup
- Doesn't work with the changes plugin