Revert to site-plugin 3.8.2
Version 3.9.0 causes

An API incompatibility was encountered while executing
org.apache.maven.plugins:maven-site-plugin:3.9.0:site:
java.lang.NoSuchMethodError:
org.codehaus.plexus.util.xml.Xpp3Dom.getInputLocation()Ljava/lang/Object;