Remove broken profile
Breaks with:

Error:  Failed to execute goal
org.apache.maven.plugins:maven-javadoc-plugin:3.7.0:javadoc
(default-cli) on project commons-fileupload2-jakarta-servlet6: An error
has occurred in Javadoc report generation:
Error:  Exit code: 1
Error:  javadoc: warning - You have specified to generate frames, by
using the --frames option.
Error:  The default is currently to not generate frames and the support
for
Error:  frames will be removed in a future release.
Error:  To suppress this warning, remove the --frames option and avoid
the use of frames.
Error: [ERROR] javadoc: error - Error fetching URL:
https://jakarta.ee/specifications/platform/10/apidocs/
Error:  Command line was: /usr/lib/jvm/temurin-11-jdk-amd64/bin/javadoc
@options @packages
Error:
Error:  Refer to the generated Javadoc files in
'/home/runner/work/commons-fileupload/commons-fileupload/commons-fileupload2-jakarta-servlet6/target/site/apidocs'
dir.
Error:  -> [Help 1]

Using Java 11

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: /usr/share/apache-maven-3.8.8
Java version: 11.0.23, vendor: Eclipse Adoptium, runtime:
/usr/lib/jvm/temurin-11-jdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "6.5.0-1024-azure", arch: "amd64", family:
"unix"

See on GitHub CI failure like
https://github.com/apache/commons-fileupload/actions/runs/10117990274/job/27984018336